version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Debug
platform: Any CPU
before_build:
- ps: nuget restore src/vpm/vpm.sln -verbosity quiet
build:
  project: src/vpm/vpm.sln
  verbosity: minimal
artifacts:
- path: src/vpm/deploy
  name: vpm
deploy:
- provider: GitHub
  auth_token:
    secure: YQ0zEVewHeKx2BEx2KQZV/n7rjTzeY+p8q5Zc78XYlUG/jBGyj8LXlM47ipy/zcW
  artifact: vpm
